org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon = false

# Mc stuff
minecraft_version = 1.21.1
minecraft_min_version = 1.21
minecraft_max_version = 1.21.1
minecraft_supported_versions=1.21.1

# Mod stuff
mod_id = farmersdelight
mod_name = Farmer's Delight
mod_version = 1.21.1-3.2.5
mod_license = MIT License
mod_group_id = vectorwing
mod_authors = MehVahdJukaar, ChrysanthCow, cassiancc
mod_description = A cozy expansion to farming and cooking!
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated
mod_github = https://github.com/MehVahdJukaar/FarmersDelightRefabricated
mod_credits = vectorwing

curseforge_project_id = 993166
modrinth_project_id = 7vxePowz

# Loaders
parchment_version = 1.21.1:2024.11.17

fabric_loader_version = 0.16.14
fabric_api_version = 0.116.8+1.21.1

# Dependency Info
fabric_asm_version = v2.3
jei_version = 19.9.0.121
rei_version = 16.0.799
emi_version = 1.1.12+1.21
eiv_version = 2.4.2
appleskin_version = mc1.21-3.0.5
crafttweaker_version = 21.0.2
crafttweaker_ap_version = 3.0.0.15
modmenu_version = 11.0.3

cloth_version = 15.0.140
